### PR TITLE
feat/sso

### PR DESCRIPTION
**Pull request by ratan2020cs131**
1. we are now able to open sso-link by clicking on 'SSO Login' button from UI.
2. after successful authentication from sso-link it redirects us to 'privateline://' protocol, which is the deep link i settled up for out desktop app.
3. when we are redirected to the app, it is able to capture the 'session_state' & 'code'

privatline-sso1

### CODE REVIEW

**Comment by ratan2020cs131** [comment]
Do not merge yet,
this sso is working on dev env currently, we need the `client_id` for prod sso and have to set redirect_uri to `privateline://auth`

**Comment by kocmo** [comment]
@ksatyarth2, @ratan2020cs131, @sandeepinigithub, @swapnilsparsh - could you please contact Deepak?

**Comment by kocmo** [comment]
@swapnilsparsh, @ratan2020cs131 - is the SSO feature ready for testing, and PR ready for merge?

**Comment by ratan2020cs131** [comment]
> @swapnilsparsh, @ratan2020cs131 - is the SSO feature ready for testing, and PR ready for merge?

@kocmo yes, it is ready for testing

**Review by swapnilsparsh — APPROVED** [review]

**Review by kocmo — CHANGES_REQUESTED** [review]
SSO login doesn't work for me on Linux, Debian 12 with Brave browser. I granted browser permission to open the links of requested type in PL Connect UI. I click "SSO Login", browser blips, nothing happens in the browser or in PL Connect UI.

Console log for PL Connect UI has:

```
Opening in existing browser session.
The second app instance was tried to start.
privateLINE UI triggered from --->   --streaming-schemes
```

**Review by swapnilsparsh — APPROVED** [review]

**Comment by kocmo** [comment]
Looks good, tested SSO and non-SSO on Debian 12 and Ubuntu 24.04 - merging.

**Pull request merged**
