### PR TITLE
feature: added plan expiry check while connecting to vpn

### PR DESCRIPTION
**Pull request by ratan2020cs131**

### CODE REVIEW

**Review by kocmo — APPROVED** [review]
Looks good.

Make sure you run `npm audit fix --force` when UI build reports vulnerabilities.

**Comment by swapnilsparsh** [comment]
@kocmo I've made some new changes, and the pull request is now ready for your review. Thank you

**Review by kocmo — CHANGES_REQUESTED** [review]
@swapnilsparsh, @ratan2020cs131 - you need to move the subscription checks from UI into daemon, because it's possible to use other clients (CLI) to tell daemon to switch to Total Shield, to connect, etc. Daemon is the central decision point for policy decisions.

**Comment by kocmo** [comment]
@swapnilsparsh, @ratan2020cs131, @sandeepinigithub - you should also check the thread in the chat, let's sync up there.

**Pull request merged**
