### PR TITLE
Shield and Total Shield Button UI Change

### PR DESCRIPTION
**Pull request by sandeepinigithub**
1. Added new UI of buttons
2. Added Connection type text and set its UI as per screen received

### CODE REVIEW

**Comment by kocmo** [comment]
@sandeepinigithub - thank you. I added a commit to make Shield, Total Shield buttons more rounded, to match the style of On/Off slider.

Also wanted to ask - can you please have the button colors behave the same as in PL Connect Android:
- If connected in Shield mode, then On and Shield buttons both the same color, green
- If connected in Total Shield mode, then On and Total Shield buttons both the same color, blue

Screenshots:

blue
green

**Comment by kocmo** [comment]
@sandeepinigithub - you should also join PL Comms for dev discussion

**Comment by sandeepinigithub** [comment]
@kocmo @swapnilsparsh @ksatyarth2 
Please review and merge 
Suggestions and feedback are most welcomed.

**Review by swapnilsparsh — APPROVED** [review]

**Comment by kocmo** [comment]
@sandeepinigithub - thank you for the changes. There is one bug, though. I was testing on Linux. Reproduction steps:

1. Leave PL Connect configured as Total Shield.
2. Upgrade to new build, this will stop the UI client and the service.
3. Restart UI client, connect. Total Shield button and On button will show in green.

total_shield_green_on_start bug

**Review by kocmo — CHANGES_REQUESTED** [review]
Need to fix the [bug mentioned in the last comment](https://github.com/swapnilsparsh/devsVPN/pull/16#issuecomment-2241302339)

**Comment by kocmo** [comment]
Ok, fixed this bug it in commit [24088f1](https://github.com/swapnilsparsh/devsVPN/pull/16/commits/24088f12d93d7e04af8d17cd504a8437123239f2). It's unfortunate you guys didn't find time to fix this. Merging.

**Pull request merged**
